version: 2
executorType: docker
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run: echo "Attempting checkout."
      - checkout
      - run: echo "Installing dependencies..."
      - run: npm install
      - run: echo "Attempting build..."
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run: echo "Attempting deployment..."
      - run: sudo npm install firebase-tools
      - run:
             name: Deploy Master to Firebase
             command: ln -s ./node_modules/.bin/firebase . && \ ./firebase --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master